services:
  postgres-vetro:
    image: postgres:latest
    # ports:
    #   - 12345:5432
    volumes:
      - $DB_DIR:/var/lib/postgresql/data
    env_file:
      - ../postgres/.env
  main-vetro:
    image: xdroid173/vetro:v0.0.3
    ports:
      - 3001:$EXPRESS_PORT
    # build: ../..
    depends_on:
      - postgres-vetro
    env_file:
      - .env
      - ../postgres/.env
