name: Build & Test Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag xdroid173/vetro:${{ github.ref_name }} --tag xdroid173/vetro:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags:
        - xdroid173/vetro:${{ github.ref_name }}
        - xdroid173/vetro:latest
